name: CI Build

on:
    push:
        branches: ["main"]

jobs: 
    build-linux:
        runs-on: ubuntu-latest

        steps: 
            - name: Checkout
              uses: actions/checkout@v4
              with:
                submodules: recursive

            - name: Setup vlang
              uses: vlang/setup-v@v1.4

            - name: Raylib depends
              run: sudo apt-get install -y libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev

            - name: Build raylib
              working-directory: ./client
              run: make

            - name: Build production
              working-directory: ./client
              run: make build

            - name: Upload artifacts 
              uses: actions/upload-artifact@v4
              with:
                name: linux
                path: ./client/client
